# Generated by Django 5.2.8 on 2025-11-18 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sensor",
            fields=[
                ("sensor_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, verbose_name="Назва")),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("yaremche", "Яремчанський"),
                            ("verkhovyna", "Верховинський"),
                            ("kosiv", "Косівський"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("water_level", "Рівень води"),
                            ("precipitation", "Опади"),
                        ],
                        max_length=50,
                    ),
                ),
                ("status", models.CharField(default="online", max_length=20)),
                ("latitude", models.FloatField(default=48.45)),
                ("longitude", models.FloatField(default=24.55)),
            ],
        ),
        migrations.CreateModel(
            name="SensorData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "sensor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data",
                        to="Sensors.sensor",
                    ),
                ),
            ],
        ),
    ]
